name: develop
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          
      - name: Install Bundler
        run: gem install bundler
        
      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'
          
      - name: Install Shopify CLI
        run: |
          npm install -g @shopify/cli @shopify/theme
          
      - name: Find Shopify CLI Installation Location
        run: |
          which shopify
          
      - name: Shopify Version
        run: |
          shopify --version
      
      - name: Print Current Branch
        run: echo "Current Branch: $(git rev-parse --abbrev-ref HEAD)"

      - name: Lint with Shopify Theme Check
        run: |
          shopify theme check
