name: main
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Config
        run: |
          git config --global user.email "jowell29jm@gmail.com"
          git config --global user.name "NanoDan29"
          git config credential.helper '!echo "password=${{ secrets.SHOPIFY_SECRET }}" | git-credential-store --file ~/.git-credentials store'
          
      - name: Minify JavaScript
        run: |
          npm install terser -g
          terser assets/animations.js -o assets/animations.min.js

      - name: Check for changes in JavaScript
        run: |
          if git diff --quiet; then
            echo "No changes in JavaScript files."
          else
            git add assets/animations.min.js
            git commit -m "Minify JavaScript - Auto commit"
            git push origin main
          fi

      - name: Minify CSS
        run: |
          npm install css-minify -g
          css-minify -f assets/compare.css -o assets

      - name: Check for changes in CSS
        run: |
          if git diff --quiet; then
            echo "No changes in CSS files."
          else
            git add assets/banner-text.min.css
            git commit -m "Minify CSS - Auto commit"
            git push origin main
          fi
