name: main
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'
          
      - name: Install Shopify CLI
        run: |
          npm install -g @shopify/cli@3.53.0
          
      - name: Lint with Shopify Theme Check
        run: |
          shopify theme check
