name: main
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          
      - name: Install Bundler
        run: gem install bundler
        
      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'
          
      - name: Install Shopify CLI
        run: |
          npm install -g @shopify/cli @shopify/theme
          
      - name: Find Shopify CLI Installation Location
        run: |
          which shopify
          
      - name: Shopify Version
        run: |
          shopify --version

      - name: Lint with Shopify Theme Check
        run: |
          shopify theme check

      - name: Config
        run: |
          git config --global user.email "jowell29jm@gmail.com"
          git config --global user.name "NanoDan29"
          git config credential.helper '!echo "password=${{ secrets.SHOPIFY_SECRET }}" | git-credential-store --file ~/.git-credentials store'

          
      - name: Minify JavaScript
        run: |
          npm install terser -g
          terser assets/animations.js -o assets/animations.min.js

      - name: Git status
        run: |
          git status

      - name: Check for changes in JavaScript
        run: |
          if git diff --quiet; then
            echo "No changes in JavaScript files."
          else
            git add .
            git commit -m "Minify JavaScript - Auto commit"
            git push origin main
          fi

      - name: Minify CSS
        run: |
          npm install css-minify -g
          css-minify -f assets/compare.css -o assets

      - name: Git status
        run: |
          git status

      - name: Check for changes in CSS
        run: |
          if git diff --quiet; then
            echo "No changes in CSS files."
          else
            git add .
            git commit -m "Minify CSS - Auto commit"
            git push origin main
          fi

      
