name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2  # Aquí especificas la versión de Ruby que quieres usar

    - name: Instalar dependencias
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Ejecutar theme-check
      run: |
        gem install theme-check
        theme-check

    - name: Ejecutar pruebas
      run: bundle exec rake
