name: minificacion
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Config
        run: |
          git config --global user.email "jowell29jm@gmail.com"
          git config --global user.name "NanoDan29"
          git config credential.helper '!echo "password=${{ secrets.SHOPIFY_SECRET }}" | git-credential-store --file ~/.git-credentials store'

      - name: Minify JavaScript
        run: | 
          # Verifica si el archivo de configuración existe
          if [ -f assets/javascriptFilesToMinify.json ]; then
            # Lee el archivo de configuración
            config=$(cat assets/javascriptFilesToMinify.json)
            # Extrae la lista de archivos de entrada
            filesToMinify=($(echo $config | jq -r '.javascriptFilesToMinify[].input'))

            # Verifica si la lista de archivos a minificar está vacía
            if [ ${#filesToMinify[@]} -eq 0 ]; then
              echo "Error: La lista de archivos a minificar está vacía en assets/javascriptFilesToMinify.json."
              exit 1
            fi

            # Instala Terser
            npm install terser -g
            
            cd assets

            # Realiza la minificación de JavaScript
            for file in "${filesToMinify[@]}"; do
              # Obtiene el nombre del archivo de salida
              filename=$(basename -- "$file")
              extension="${filename##*.}"
              filename="${filename%.*}"

              # Realiza la minificación
              terser $file -o assets/$filename.min.$extension
            done

            # Añade y sube los archivos minificados
            git add assets/minified
            git commit -m "Minify JavaScript"
            git push origin main
          else
            echo "Error: El archivo assets/javascriptFilesToMinify.json no existe."
          fi
