name: Minificación

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Config
        run: |
          git config --global user.email "jowell29jm@gmail.com"
          git config --global user.name "NanoDan29"
          git config credential.helper '!echo "password=${{ secrets.SHOPIFY_SECRET }}" | git-credential-store --file ~/.git-credentials store'

      - name: Minify JavaScript
        run: | 
          # Verifica si el archivo de configuración existe
          if [ -f assets/javascriptFilesToMinify.json ]; then
            # Lee el archivo de configuración
            config=$(cat assets/javascriptFilesToMinify.json)

            # Extrae la lista de archivos de entrada y nombres de salida
            filesToMinify=($(echo $config | jq -r '.javascriptFilesToMinify[].input'))
            outputNames=($(echo $config | jq -r '.javascriptFilesToMinify[].output'))

            # Verifica si la lista de archivos a minificar está vacía
            if [ ${#filesToMinify[@]} -eq 0 ]; then
              echo "Error: La lista de archivos a minificar está vacía en assets/javascriptFilesToMinify.json."
              exit 1
            fi

            # Instala Terser
            npm install terser -g

            # Cambia al directorio de assets para que Terser pueda encontrar los archivos
            cd assets

            # Realiza la minificación de JavaScript
            for i in "${!filesToMinify[@]}"; do
              file="${filesToMinify[$i]}"
              outputName="${outputNames[$i]}"

              # Verifica si el archivo de entrada existe
              if [ ! -f $file ]; then
                echo "Error: El archivo $file no existe."
                exit 1
              fi

              # Realiza la minificación
              terser $file -o $outputName
            done

          else
            echo "Error: El archivo assets/javascriptFilesToMinify.json no existe."
          fi
          
      - name: Status
        run: |
          git status
  
      - name: Commit and Push Changes
        run: |
          # Añade y sube los archivos minificados
          git add .
          git commit -m "Minify JavaScript"
          git push origin main
