name: minificacion
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Minify JavaScript
        run: | 
          # Verifica si el archivo de configuración existe
          if [ -f assets/javascriptFilesToMinify.json ]; then
            # Lee el archivo de configuración
            config=$(cat assets/javascriptFilesToMinify.json)
            # Extrae la lista de archivos de entrada y salidas
            filesToMinify=($(echo $config | jq -r '.javascriptFilesToMinify[] | .input'))
            outputDirectories=($(echo $config | jq -r '.javascriptFilesToMinify[] | .output'))

            # Crea el directorio de salida si no existe
            mkdir -p assets/minified

            # Instala Terser
            npm install terser -g

            # Realiza la minificación de JavaScript
            for ((i=0; i<${#filesToMinify[@]}; i++)); do
              file=assets/${filesToMinify[i]}
              outputDirectory=${outputDirectories[i]}

              # Obtiene el nombre del archivo de salida
              filename=$(basename -- "$file")
              extension="${filename##*.}"
              filename="${filename%.*}"

              # Realiza la minificación
              terser $file -o assets/minified/$filename.min.$extension
            done

            # Añade y sube los archivos minificados
            git add assets/minified
            git commit -m "Minify JavaScript"
            git push origin main
          else
            echo "Error: El archivo assets/javascriptFilesToMinify.json no existe."
          fi
