name: Minificación

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Config
        run: |
          git config --global user.email "jowell29jm@gmail.com"
          git config --global user.name "NanoDan29"
          git config credential.helper '!echo "password=${{ secrets.SHOPIFY_SECRET }}" | git-credential-store --file ~/.git-credentials store'

      - name: Minify JavaScript
        run: | 
          # Verifica si el archivo de configuración existe
          if [ -f assets/javascriptFilesToMinify.json ]; then
            # Cambia al directorio assets
            cd assets

            # Lee el archivo de configuración
            config=$(cat javascriptFilesToMinify.json)

            # Extrae la lista de archivos de entrada y nombres de salida
            filesToMinify=($(echo $config | jq -r '.javascriptFilesToMinify[].input'))
            outputNames=($(echo $config | jq -r '.javascriptFilesToMinify[].output'))

            # Verifica si la lista de archivos a minificar está vacía
            if [ ${#filesToMinify[@]} -eq 0 ]; then
              echo "Error: La lista de archivos a minificar está vacía en assets/javascriptFilesToMinify.json."
              exit 1
            fi

            # Instala Terser
            npm install terser -g

            # Realiza la minificación de JavaScript
            for i in "${!filesToMinify[@]}"; do
              file="${filesToMinify[$i]}"
              outputName="${outputNames[$i]}"

              # Verifica si el archivo de entrada existe
              if [ ! -f $file ]; then
                echo "Error: El archivo $file no existe."
                exit 1
              fi

              # Realiza la minificación dentro del directorio assets
              terser $file -o $outputName
            done

            # Vuelve al directorio raíz del repositorio
            cd ..
          else
            echo "Error: El archivo assets/javascriptFilesToMinify.json no existe."
          fi

      - name: Status
        run: |
          git status

      - name: Minify CSS
        run: |
          # Verifica si el archivo de configuración para CSS existe
          if [ -f assets/cssFilesToMinify.json ]; then
            # Lee el archivo de configuración
            cssConfig=$(cat assets/cssFilesToMinify.json)
            # Extrae la lista de archivos CSS a minificar
            cssFilesToMinify=($(echo $cssConfig | jq -r '.cssFilesToMinify[]'))

            # Verifica si la lista de archivos CSS a minificar está vacía
            if [ ${#cssFilesToMinify[@]} -eq 0 ]; then
              echo "Error: La lista de archivos CSS a minificar está vacía en assets/cssFilesToMinify.json."
              exit 1
            fi

            # Instala css-minify
            npm install css-minify -g

            # Realiza la minificación de CSS
            for cssFile in "${cssFilesToMinify[@]}"; do
              # Verifica si el archivo CSS de entrada existe
              if [ ! -f $cssFile ]; then
                echo "Error: El archivo CSS $cssFile no existe."
                exit 1
              fi

              # Realiza la minificación
              css-minify -f $cssFile -o $cssFile.min.css
              git add $cssFile.min.css
            done

          else
            echo "Error: El archivo assets/cssFilesToMinify.json no existe."
          fi
          
      - name: Status
        run: |
          git status
  
      - name: Commit and Push Changes
        run: |
          # Añade y sube los archivos minificados
          git add .
          git commit -m "Minify JS and CSS"
          git push origin main
          
